import { INodeSettings } from '../interfaces/node-settings.interface';

export var NodeSettings: INodeSettings = {
  CANVAS_WIDTH: 1400,
  CANVAS_HEIGHT: 800,
  NODE_MAX_WIDTH: 160,
  NODE_MIN_WIDTH: 100,
  NODE_RADIUS: 10,
  NODE_HEIGHT: 36,
  NODE_PADDING: 13,
  NODE_ICON_HOLDER_WIDTH: 18,
  HANDLER_WIDTH: 10,
  HANDLER_HEIGHT: 10,
  HANDLER_RADIUS: 8,
  FONT_SIZE: 13,
  PATH_STROKE_WIDTH: 1.5,
  MIN_SCALE: 0.6,
  MAX_SCALE: 3,
  RULE_SIZE: 5,
  MAP_HEIGHT: 100,
  MAP_WIDTH: 200
};