export const CanvasConstants = {
  NODE_MAX_WIDTH: 180,
  NODE_MIN_WIDTH: 100,
  NODE_RADIUS: 5,
  NODE_HEIGHT: 34,
  NODE_PADDING: 10,
  NODE_ICON_HOLDER_WIDTH: 30,

  HANDLER_WIDTH: 10,
  HANDLER_HEIGHT: 10,
  HANDLER_RADIUS: 3,

  FONT_SIZE: 13,
  PATH_STROKE_WIDTH: 2
};